### PR TITLE
misc arm64 Mac OS 11 fixes

### PR DESCRIPTION
**Pull request by lawrence-danna-apple**
I (finally) deconflicted my own branch for Mac OS 11 and arm64 with `pyobjc-7-branch`.   It turns out most of it is stuff you've already covered.    Here's a few things that are left over.

### CODE REVIEW

**Comment by lawrence-danna-apple** [comment]
Some of these changes are just small things I've found convenient for building and testing on Mac OS 11, and not strictly necessary, such as the xml test output thing, but I figure If I found it useful others may as well.

**Comment by ronaldoussoren** [comment]
Thanks.

I noticed that my workaround for the shared library cache no longer works in beta 3, I'll have to use _dyld_shared_cache_contains_path after all.

**Comment by lawrence-danna-apple** [comment]
rebased, removed the patches you rewrote, and added a fix for `test_version_current`

**Comment by lawrence-danna-apple** [comment]
> Thanks.
> 
> I noticed that my workaround for the shared library cache no longer works in beta 3, I'll have to use _dyld_shared_cache_contains_path after all.

yea, it should be a real API in beta 4 .

**Comment by lawrence-danna-apple** [comment]
all this is obsoleted i think by upstream changes.

**Pull request closed without merging**
